credentials:
  usernames:
    jsmith:
      email: jsmith@gmail.com
      name: John Smith
      password: '$2b$12$vzhaYf2FlV4/fZPXDimVNOWqm5e2EoSx5YJa30Ffvk8dhfMOHg4XW'
    rbriggs:
      email: rbriggs@gmail.com
      name: Rebecca Briggs
      password: '$2b$12$CgPB5sZubvzRhjGsdLbCH.DksmFqWkoOugYeQq28yko2HHZjTq9ze'
cookie:
  expiry_days: 30
  key: some_signature_key
  name: some_cookie_name
preauthorized:
  emails:
  - melsby@gmail.com
  